# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "aclogin" = super.buildPythonPackage rec {
    pname = "aclogin";
    version = "0.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/a2/f7b71a643750c0044cdc7a6226ea54073b0263f8abb4e4277b79ba0fc53d/aclogin-0.2.1-py3-none-any.whl";
      sha256 = "1j9pm3vfkp0ih4ply9adlhlmw3vx67kdman64pwkwap6v12zwflc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."appdirs"
    ];
  };
  "appdirs" = super.buildPythonPackage rec {
    pname = "appdirs";
    version = "1.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl";
      sha256 = "0a5ib82s2335nhvq5rjh8hkimrwyw43xnshn3ds8lccrdg6xlhd8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
